import 'dart:convert';
import 'package:http/http.dart' as http;
import '../models/models.dart';
import '../models/quiz_models.dart';
import 'prompt_service.dart';

class GeminiService {
  final String apiKey;
  final String baseUrl = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-pro-preview:generateContent';

  GeminiService({required this.apiKey});

  Future<Quiz?> generateQuizFromText({
    required String content,
    required QuizConfig config,
    required String source,
  }) async {
    try {
      final systemPrompt = PromptService.buildSystemPrompt();
      final userPrompt = PromptService.buildUserPrompt(
        quizType: config.quizType,
        questionCount: config.numQuestions,
        difficulty: config.difficulty,
        content: content,
      );

      final response = await http.post(
        Uri.parse('$baseUrl?key=$apiKey'),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          'contents': [
            {
              'parts': [
                {'text': '$systemPrompt\n\n$userPrompt'}
              ]
            }
          ],
          'generationConfig': {
            'temperature': 0.1,
            'responseMimeType': 'application/json',
          }
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        final text = data['candidates'][0]['content']['parts'][0]['text'] as String;
        return _parseQuizFromResponse(text, source);
      } else {
        print('Gemini API Error: ${response.statusCode} - ${response.body}');
        return null;
      }
    } catch (e) {
      print('Quiz Generation Error: $e');
      return null;
    }
  }

  Quiz? _parseQuizFromResponse(String text, String source) {
    try {
      // Robust JSON extraction
      String jsonStr = text;
      if (text.contains('```json')) {
        jsonStr = text.split('```json').last.split('```').first.trim();
      } else if (text.contains('```')) {
        jsonStr = text.split('```').last.split('```').first.trim();
      }

      final data = jsonDecode(jsonStr);
      final questions = <QuizQuestion>[];

      for (var q in data['questions']) {
        questions.add(QuizQuestion(
          id: q['id']?.toString() ?? 'q_${questions.length}',
          type: _parseType(q['type']),
          prompt: q['prompt'] as String,
          choices: q['choices'] != null ? List<String>.from(q['choices']) : null,
          answerIndex: q['answerIndex'],
          answers: q['answers'] != null ? List<String>.from(q['answers']) : null,
          pairs: q['pairs'] != null
            ? (q['pairs'] as List).map((p) => MatchingPair(left: p['left'], right: p['right'])).toList()
            : null,
          explanation: q['explanation'] ?? '',
        ));
      }

      return Quiz(
        id: 'quiz_${DateTime.now().millisecondsSinceEpoch}',
        title: data['quiz_title'] ?? 'AI-Generated Quiz',
        description: data['source_summary'] ?? 'Generated by Gemini AI',
        questions: questions,
        createdAt: DateTime.now(),
        source: source,
        sourceSummary: data['source_summary'] ?? '',
      );
    } catch (e) {
      print('Parse Quiz Error: $e');
      return null;
    }
  }

  QuestionType _parseType(String? type) {
    switch (type) {
      case 'mcq': return QuestionType.mcq;
      case 'true_false': return QuestionType.true_false;
      case 'fill_blank': return QuestionType.fill_blank;
      case 'identification': return QuestionType.identification;
      case 'matching': return QuestionType.matching;
      default: return QuestionType.mcq;
    }
  }

  Future<List<Flashcard>?> generateFlashcards({required String content}) async {
    try {
      final prompt = PromptService.buildFlashcardPrompt(content);
      final response = await http.post(
        Uri.parse('$baseUrl?key=$apiKey'),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          'contents': [{'parts': [{'text': prompt}]}],
          'generationConfig': {'temperature': 0.1, 'responseMimeType': 'application/json'}
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        final text = data['candidates'][0]['content']['parts'][0]['text'] as String;
        final list = jsonDecode(text) as List;
        return list.map((e) => Flashcard.fromJson(e)).toList();
      }
    } catch (e) {
      print('Flashcard Generation Error: $e');
    }
    return null;
  }

  Future<String?> generateReviewerNotes({required String content}) async {
    try {
      final prompt = PromptService.buildReviewerPrompt(content);
      final response = await http.post(
        Uri.parse('$baseUrl?key=$apiKey'),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          'contents': [{'parts': [{'text': prompt}]}],
          'generationConfig': {'temperature': 0.3}
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return data['candidates'][0]['content']['parts'][0]['text'] as String;
      }
    } catch (e) {
      print('Reviewer Notes Generation Error: $e');
    }
    return null;
  }

  Future<String?> explainAnswer({
    required String question,
    required String userAnswer,
    required String correctAnswer,
    required String context,
  }) async {
    try {
      final prompt = PromptService.buildExplanationPrompt(
        question: question,
        userAnswer: userAnswer,
        correctAnswer: correctAnswer,
        context: context,
      );
      final response = await http.post(
        Uri.parse('$baseUrl?key=$apiKey'),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          'contents': [{'parts': [{'text': prompt}]}],
          'generationConfig': {'temperature': 0.3}
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return data['candidates'][0]['content']['parts'][0]['text'] as String;
      }
    } catch (e) {
      print('Gemini Explanation Error: $e');
    }
    return null;
  }

  Future<String?> chat({required String message, List<ChatMessage> history = const []}) async {
    try {
      final response = await http.post(
        Uri.parse('$baseUrl?key=$apiKey'),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          'contents': [
            ...history.map((m) => {
                  'role': m.isUser ? 'user' : 'model',
                  'parts': [
                    {'text': m.text}
                  ]
                }),
            {
              'role': 'user',
              'parts': [
                {'text': message}
              ]
            }
          ],
          'generationConfig': {'temperature': 0.7}
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return data['candidates'][0]['content']['parts'][0]['text'] as String;
      }
    } catch (e) {
      print('Gemini Chat Error: $e');
    }
    return null;
  }
}
