import 'dart:convert';
import 'package:http/http.dart' as http;
import '../models/models.dart';
import '../models/quiz_models.dart';
import 'prompt_service.dart';

class GrokService {
  final String apiKey;
  final String baseUrl = 'https://api.x.ai/v1/chat/completions';

  GrokService({required this.apiKey});

  Future<Quiz?> generateQuizFromText({
    required String content,
    required QuizConfig config,
    required String source,
  }) async {
    try {
      final systemPrompt = PromptService.buildSystemPrompt();
      final userPrompt = PromptService.buildUserPrompt(
        quizType: config.quizType,
        questionCount: config.numQuestions,
        difficulty: config.difficulty,
        content: content,
      );

      final response = await http.post(
        Uri.parse(baseUrl),
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer $apiKey',
        },
        body: jsonEncode({
          'model': 'grok-2-1212',
          'messages': [
            {'role': 'system', 'content': systemPrompt},
            {'role': 'user', 'content': userPrompt}
          ],
          'temperature': 0.1,
          'response_format': {'type': 'json_object'}
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        final text = data['choices'][0]['message']['content'] as String;
        return _parseQuizFromResponse(text, source);
      } else {
        print('Grok API Error: ${response.statusCode} - ${response.body}');
        return null;
      }
    } catch (e) {
      print('Grok Quiz Generation Error: $e');
      return null;
    }
  }

  Quiz? _parseQuizFromResponse(String text, String source) {
    try {
      String jsonStr = text;
      if (text.contains('```json')) {
        jsonStr = text.split('```json').last.split('```').first.trim();
      } else if (text.contains('```')) {
        jsonStr = text.split('```').last.split('```').first.trim();
      }

      final data = jsonDecode(jsonStr);
      final questions = <QuizQuestion>[];

      for (var q in data['questions']) {
        questions.add(QuizQuestion(
          id: q['id']?.toString() ?? 'gq_${questions.length}',
          type: _parseType(q['type']),
          prompt: q['prompt'] as String,
          choices: q['choices'] != null ? List<String>.from(q['choices']) : null,
          answerIndex: q['answerIndex'],
          answers: q['answers'] != null ? List<String>.from(q['answers']) : null,
          pairs: q['pairs'] != null
            ? (q['pairs'] as List).map((p) => MatchingPair(left: p['left'], right: p['right'])).toList()
            : null,
          explanation: q['explanation'] ?? '',
        ));
      }

      return Quiz(
        id: 'quiz_grok_${DateTime.now().millisecondsSinceEpoch}',
        title: data['quiz_title'] ?? 'Grok-Generated Quiz',
        description: data['source_summary'] ?? 'Generated by Grok AI',
        questions: questions,
        createdAt: DateTime.now(),
        source: source,
        sourceSummary: data['source_summary'] ?? '',
      );
    } catch (e) {
      print('Parse Grok Quiz Error: $e');
      return null;
    }
  }

  QuestionType _parseType(String? type) {
    switch (type) {
      case 'mcq': return QuestionType.mcq;
      case 'true_false': return QuestionType.true_false;
      case 'fill_blank': return QuestionType.fill_blank;
      case 'identification': return QuestionType.identification;
      case 'matching': return QuestionType.matching;
      default: return QuestionType.mcq;
    }
  }

  Future<List<Flashcard>?> generateFlashcards({required String content}) async {
    try {
      final prompt = PromptService.buildFlashcardPrompt(content);
      final response = await http.post(
        Uri.parse(baseUrl),
        headers: {'Content-Type': 'application/json', 'Authorization': 'Bearer $apiKey'},
        body: jsonEncode({
          'model': 'grok-2-1212',
          'messages': [{'role': 'user', 'content': prompt}],
          'temperature': 0.1,
          'response_format': {'type': 'json_object'}
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        final text = data['choices'][0]['message']['content'] as String;
        final decoded = jsonDecode(text);
        // Grok might return {"flashcards": [...]} or just the array.
        // Prompt asks for array, but response_format: json_object might force a wrapper.
        final list = (decoded is List) ? decoded : decoded['flashcards'] as List;
        return list.map((e) => Flashcard.fromJson(e)).toList();
      }
    } catch (e) {
      print('Grok Flashcard Error: $e');
    }
    return null;
  }

  Future<String?> generateReviewerNotes({required String content}) async {
    try {
      final prompt = PromptService.buildReviewerPrompt(content);
      final response = await http.post(
        Uri.parse(baseUrl),
        headers: {'Content-Type': 'application/json', 'Authorization': 'Bearer $apiKey'},
        body: jsonEncode({
          'model': 'grok-2-1212',
          'messages': [{'role': 'user', 'content': prompt}],
          'temperature': 0.3
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return data['choices'][0]['message']['content'] as String;
      }
    } catch (e) {
      print('Grok Reviewer Notes Error: $e');
    }
    return null;
  }

  Future<String?> explainAnswer({
    required String question,
    required String userAnswer,
    required String correctAnswer,
    required String context,
  }) async {
    try {
      final prompt = PromptService.buildExplanationPrompt(
        question: question,
        userAnswer: userAnswer,
        correctAnswer: correctAnswer,
        context: context,
      );
      final response = await http.post(
        Uri.parse(baseUrl),
        headers: {'Content-Type': 'application/json', 'Authorization': 'Bearer $apiKey'},
        body: jsonEncode({
          'model': 'grok-2-1212',
          'messages': [{'role': 'user', 'content': prompt}],
          'temperature': 0.3
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return data['choices'][0]['message']['content'] as String;
      }
    } catch (e) {
      print('Grok Explanation Error: $e');
    }
    return null;
  }

  Future<String?> chat({required String message, List<ChatMessage> history = const []}) async {
    try {
      final response = await http.post(
        Uri.parse(baseUrl),
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer $apiKey',
        },
        body: jsonEncode({
          'model': 'grok-2-1212',
          'messages': [
            ...history.map((m) => {'role': m.isUser ? 'user' : 'assistant', 'content': m.text}),
            {'role': 'user', 'content': message}
          ],
          'temperature': 0.7
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return data['choices'][0]['message']['content'] as String;
      }
    } catch (e) {
      print('Grok Chat Error: $e');
    }
    return null;
  }
}
